/*
 * This source file was generated by the Gradle 'init' task
 */
package ejerciciopokemonpropio;

public class App {
    
    public static void main(String[] args) {
        
        Squirtle squirtle = new Squirtle (10,"Masculino");
        Charmander charmander = new Charmander (30,"Femenino");
        Bulbasaur bulba = new Bulbasaur (12,"Femenino");
        Pikachu pika = new Pikachu(3,"Masculino");
        
        squirtle.atacarAraniazo();
        squirtle.atacarHidrobomba();
        charmander.atacarAraniazo();
        charmander.atacarLanzallamas();
        bulba.atacarAraniazo();
        bulba.atacarDrenadoras();
        pika.atacarAraniazo();
        pika.atacarImpactrueno();
        
        System.out.println("No te olvides de suscribirte a TodoCode ");

    }
}
